# Conexus Configuration Example
# Copy this to config.yml and customize as needed
# Environment variables take precedence over file config

server:
  host: "0.0.0.0"
  # port: 0

database:
  path: "./data/conexus.db"

indexer:
  root_path: "."
  chunk_size: 512
  chunk_overlap: 50

logging:
  level: "info"  # debug, info, warn, error
  format: "json" # json, text
